project_id = "hlbbaaewjebasisxgnrt"

[functions.create-mercadopago-preference]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false

[functions.test-mercadopago-connection]
verify_jwt = false
